### PR TITLE
from and to on SerializerRepo

### PR DESCRIPTION
**Pull request by tejainece**

### CODE REVIEW

**Comment by lejard-h** [comment]
we changed `to` and `from` to `serialize` and `deserialize` on the `Serializer` class because it was confusing, but now for the repository, it start to be confusing, there is `serialize`, `encode`, `to` then `deserialize`, `decode`, `from`.

But I don't understand the change, a `SerializerRepo` without the implementation of `encode` and `decode` will have the same effect

**Comment by tejainece** [comment]
all of them are necessary.

Sometimes, you don't want to encode and decode, you just want to convert to Map and from Map. Right now, there is no easy way to do that on `SerializerRepo`.

**Comment by lejard-h** [comment]
this
```dart
SerializerRepo repo = new SerializerRepo();
repo.serialize();
```
will have the same effect has this
```dart
JsonRepo repo = new JsonRepo();
repo.to();
```

if someone use `JsonRepo` it is to convert to JSON not Dart Object, you have `SerializerRepo` for this.

**Comment by tejainece** [comment]
No. It is a `JsonRepo` not `SerializerRepo`. Sometimes you don't want to serialize directly to JSON. You want to do it yourself, for whatever reason.

**Comment by tejainece** [comment]
Here is one example:

https://github.com/Jaguar-dart/jaguar_client/blob/master/lib/src/client.dart#L121

It is going to be encoded as url-encoded-form. But if it is just a flat Dart object, same repo can be used for both json and form. In this case, you dont want to serialize. You just want the Map.

**Comment by lejard-h** [comment]
In that case why are you not using `SerializerRepo` instead of `JsonRepo` ?

**Comment by tejainece** [comment]
Because you cannot use 2 different repos.

**Pull request merged**
