### PR TITLE
fix for cases that a double field contains string without decimal point

### PR DESCRIPTION
**Pull request by escamoteur**
See https://github.com/Jaguar-dart/jaguar_serializer/issues/181

### CODE REVIEW

**Comment by escamoteur** [comment]
I love jaguar_serializer and when I can fix a bug myself I'm happy

**Comment by escamoteur** [comment]
Hi,
could you please merge this PR?
Thanks
THomas

**Comment by jaumard** [comment]
@tejainece can you take a look please.

**Comment by jaumard** [comment]
Thanks @escamoteur for the fix !

**Pull request merged**
